# Github Action to generate a snake eating contributions graph
# name of workflow:
name: Generate Snake

# root key on, when to run the action
on:
  schedule:
    # cron job for every 12 hours
    - cron: "0 */12 * * *"

    # cmd allowing to run action automatically from the actions tab
  workflow_dispatch:

  # also run on every push on main branch
  push:
      branches:
      - main

  # the sequence of jobs(steps) on this workflow
jobs:

  # this workflow contains a single job called build
    build:
      # the type of runner job will run on
      runs-on: ubuntu-latest

      steps:
        - name: Clone repo
          uses: actions/checkout@v3

        - name: Generate snake files in './dist/' directory
          uses: Platane/snk@v2
          id: snake-gif
          # env vars for action
          with:
            github_user_name: ${{github.repository_owner}}
            outputs:
              dist/github-contribution-grid-snake.svg
              dist/github-contribution-grid-snake-dark.svg?palette=github-dark
              dist/github-contribution-grid-snake.gif?color_snake=pink&color_dots=#bff6f2,#e6da00,#0000e6,#e64900,#00e654
              
          # for debugging    
        - name: Show build status
          run: git status


        - name: Push new files to the output branch
          uses: crazy-max/ghaction-github-pages@v3.1.0
          with: 
            target_branch: output
            build_dir: dist
            commit_message: update snake animation

          
          env:
          # automatic to check if action has push permissions to our repo
            GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
     
    


